version: '3.8'

services:
  cassandra:
    image: cassandra:4.1.0
    restart: always
    ports:
      - '9042:9042'
    environment:
      - CASSANDRA_CLUSTER_NAME=akka-bank-account-cluster
    volumes:
      - cassandra:/var/lib/cassandra

volumes:
  cassandra: